import { useMemo, useState, type Dispatch, type SetStateAction } from "react";
import { Archive, ArrowRightLeft, BedDouble, CalendarDays, CircleAlert, Clock3, Eye, FilterX, History, Landmark, LogOut, Mail, MoreHorizontal, Pencil, Phone, Plus, Printer, ReceiptText, Search, ShieldCheck, Trash2, UserRound, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ErrorBanner, FieldError } from "@/components/ui/error-banner";
import { PaginationControls } from "@/components/ui/pagination";
import { ListSkeleton } from "@/components/ui/skeleton";
import { useToast } from "@/components/ui/toast";
import { useNeeds } from "@/features/needs/application/needs-provider";
import { usePayments } from "@/features/payments/application/payments-provider";
import { useSpaces } from "@/features/spaces/application/spaces-provider";
import type { BillingCharge, BoarderOccupancy, LeaseTerm, Need, Payment, Tenant } from "@/lib/bedkeep/types";
import { zonedDateKey, zonedMonthKey } from "@/lib/local-date";
import { usePagination } from "@/lib/use-pagination";
import { duplicateError, emailError, normalizePhone, normalizeText, phoneError } from "@/lib/validation";
import { useUnsavedChanges } from "@/lib/use-unsaved-changes";
import { userError } from "@/lib/user-error";

const peso = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", maximumFractionDigits: 0 });
const dateLabel = (value?: string) => value ? new Date(`${value}T00:00:00`).toLocaleDateString("en-PH", { month: "short", day: "numeric", year: "numeric" }) : "Present";
type ConfirmAction = { type: "moveout" | "archive" | "delete"; boarder: Tenant };
type DetailTab = "overview" | "lease" | "payments" | "history" | "requests";
type BoarderSort = "name" | "balance-high" | "bedspace";

export function TenantsView({ onRecordPayment, onAssignBoarder }: { onRecordPayment: (boarderId: string) => void; onAssignBoarder: () => void }) {
  const { boarders, beds, occupancyHistory, property, createBoarder, updateBoarder, transferBoarder, moveOutBoarder, archiveBoarder, deleteBoarder, loading, mutating, error, refresh } = useSpaces();
  const { payments, charges, leaseTerms } = usePayments();
  const { needs } = useNeeds();
  const { push } = useToast();
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<"active" | "overdue" | "unassigned" | "inactive" | "all">("active");
  const [sort, setSort] = useState<BoarderSort>("name");
  const [addOpen, setAddOpen] = useState(false);
  const [edit, setEdit] = useState<Tenant | null>(null);
  const [transfer, setTransfer] = useState<Tenant | null>(null);
  const [targetBedId, setTargetBedId] = useState("");
  const [confirm, setConfirm] = useState<ConfirmAction | null>(null);
  const [detailId, setDetailId] = useState<string | null>(null);
  const [detailTab, setDetailTab] = useState<DetailTab>("overview");
  const [form, setForm] = useState({ fullName: "", phone: "", email: "" });
  const [formBaseline, setFormBaseline] = useState("");
  const vacantBeds = beds.filter((bed) => bed.status === "vacant");
  const selectedBoarder = boarders.find((boarder) => boarder.id === detailId) || null;
  const filtered = useMemo(() => boarders.filter((item) => {
    const matches = `${item.name} ${item.bed} ${item.phone} ${item.email || ""}`.toLowerCase().includes(query.toLowerCase());
    const matchesStatus = filter === "all" || filter === "active" && ["current", "overdue"].includes(item.status) || item.status === filter;
    return matches && matchesStatus;
  }).sort((a, b) => sort === "balance-high" ? b.balance - a.balance : sort === "bedspace" ? a.bed.localeCompare(b.bed) : a.name.localeCompare(b.name)), [boarders, filter, query, sort]);
  const pagination = usePagination(filtered, 8, `${query}|${filter}|${sort}`);
  const dirty = (addOpen || Boolean(edit)) && Boolean(formBaseline) && JSON.stringify(form) !== formBaseline;
  const guardClose = useUnsavedChanges(dirty);
  const comparableBoarders = boarders.filter((item) => item.id !== edit?.id);
  const formErrors = { name: !normalizeText(form.fullName) ? "Full name is required." : duplicateError(form.fullName, comparableBoarders.map((item) => item.name), "A boarder with this name"), phone: phoneError(form.phone), email: emailError(form.email) };
  const hasFormError = Boolean(formErrors.name || formErrors.phone || formErrors.email);

  function openAdd() { const next = { fullName: "", phone: "", email: "" }; setForm(next); setFormBaseline(JSON.stringify(next)); setAddOpen(true); }
  function openEdit(item: Tenant) { setDetailId(null); const next = { fullName: item.name, phone: item.phone === "No phone" ? "" : item.phone, email: item.email || "" }; setForm(next); setFormBaseline(JSON.stringify(next)); setEdit(item); }
  function closeForm() { guardClose(() => { setAddOpen(false); setEdit(null); }); }
  function openTransfer(item: Tenant) { setDetailId(null); setTransfer(item); setTargetBedId(vacantBeds[0]?.id || ""); }
  function openDetail(item: Tenant) { setDetailId(item.id); setDetailTab("overview"); }
  function openConfirmation(type: ConfirmAction["type"], boarder: Tenant) { setDetailId(null); setConfirm({ type, boarder }); }
  async function saveNew() { if (hasFormError) return; try { const input = { fullName: normalizeText(form.fullName), phone: form.phone.trim(), email: form.email.trim() }; await createBoarder(input); setFormBaseline(JSON.stringify(form)); setAddOpen(false); setQuery(""); setFilter("unassigned"); push({ title: "Boarder added", description: "The record is ready for bedspace assignment." }); } catch (caught) { push({ tone: "error", title: "Boarder could not be added", description: userError(caught, "Please check the details and retry.") }); } }
  async function saveEdit() { if (!edit || hasFormError) return; try { await updateBoarder(edit.id, { fullName: normalizeText(form.fullName), phone: form.phone.trim(), email: form.email.trim() }); setFormBaseline(JSON.stringify(form)); setEdit(null); push({ title: "Boarder updated" }); } catch (caught) { push({ tone: "error", title: "Boarder could not be updated", description: userError(caught, "Please retry the update.") }); } }
  async function saveTransfer() { if (!transfer || !targetBedId) return; const bed = vacantBeds.find((item) => item.id === targetBedId); try { await transferBoarder(transfer.id, targetBedId, bed?.rent || 0); setTransfer(null); setTargetBedId(""); push({ title: transfer.status === "unassigned" ? "Boarder assigned" : "Boarder transferred", description: bed ? `${bed.room} · ${bed.label}` : undefined }); } catch (caught) { push({ tone: "error", title: "Transfer failed", description: userError(caught, "Please retry the bedspace change.") }); } }
  async function runConfirm() { if (!confirm) return; try { if (confirm.type === "moveout") await moveOutBoarder(confirm.boarder.id, zonedDateKey(new Date(), property?.timezone)); else if (confirm.type === "archive") await archiveBoarder(confirm.boarder.id); else await deleteBoarder(confirm.boarder.id); push({ title: confirm.type === "moveout" ? "Move-out recorded" : confirm.type === "archive" ? "Boarder archived" : "Boarder removed" }); setConfirm(null); } catch (caught) { push({ tone: "error", title: "Action could not be completed", description: userError(caught, "Please retry this action.") }); } }

  return <div className="view-stack animate-in-view">
    <div className="section-intro"><div><span className="eyebrow">BOARDER DIRECTORY</span><h2>People, not spreadsheet rows.</h2><p>Open a boarder profile to review their stay, balance, payments, and requests in one place.</p></div><Button className="lime-button" onClick={openAdd}><Plus /> Add boarder</Button></div>
    {error && <ErrorBanner message={error} onRetry={refresh} retrying={loading} />}
    <div className="directory-filter-panel"><div className="directory-controls"><label className="search-field"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, bed, phone, or email" aria-label="Search boarders" /></label><div className="filter-tabs" role="group" aria-label="Boarder status">{(["active", "overdue", "unassigned", "inactive", "all"] as const).map((item) => <button key={item} className={filter === item ? "active" : ""} aria-pressed={filter === item} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="compact-filter-row"><label><span>Sort boarders</span><select value={sort} onChange={(event) => setSort(event.target.value as BoarderSort)}><option value="name">Name A–Z</option><option value="balance-high">Highest balance</option><option value="bedspace">Bedspace</option></select></label>{(query || filter !== "active" || sort !== "name") && <Button variant="outline" onClick={() => { setQuery(""); setFilter("active"); setSort("name"); }}><FilterX /> Clear filters</Button>}</div></div>
    {loading ? <ListSkeleton rows={6} /> : <div className="tenant-list">{pagination.visible.map((tenant) => <BoarderRow key={tenant.id} tenant={tenant} hasVacancy={Boolean(vacantBeds.length)} onView={() => openDetail(tenant)} onEdit={() => openEdit(tenant)} onTransfer={() => tenant.status === "unassigned" ? onAssignBoarder() : openTransfer(tenant)} onMoveOut={() => openConfirmation("moveout", tenant)} onArchive={() => openConfirmation("archive", tenant)} onDelete={() => openConfirmation("delete", tenant)} />)}{!filtered.length && <div className="list-empty"><UserRound /><strong>{query ? "No matching boarders" : `No ${filter} boarders`}</strong><span>{query ? "Try a different name, bedspace, phone number, or email." : filter === "unassigned" ? "New boarders appear here until you assign them a bedspace." : "Boarders will appear here when records match this filter."}</span>{!query && filter === "unassigned" && <Button className="lime-button" onClick={openAdd}><Plus /> Add boarder</Button>}</div>}</div>}
    <PaginationControls {...pagination} total={filtered.length} label="boarders" onPageChange={pagination.setPage} />

    <BoarderDetailsDrawer boarder={selectedBoarder} payments={payments.filter((item) => item.boarderId === detailId)} charges={charges.filter((item) => item.boarderId === detailId)} lease={leaseTerms.find((item) => item.boarderId === detailId && item.status === "active") || null} history={occupancyHistory.filter((item) => item.boarderId === detailId)} needs={needs.filter((item) => item.boarderId === detailId)} timezone={property?.timezone || "Asia/Manila"} tab={detailTab} setTab={setDetailTab} hasVacancy={Boolean(vacantBeds.length)} onClose={() => setDetailId(null)} onEdit={() => selectedBoarder && openEdit(selectedBoarder)} onTransfer={() => { if (!selectedBoarder) return; if (selectedBoarder.status === "unassigned") { setDetailId(null); onAssignBoarder(); } else openTransfer(selectedBoarder); }} onRecordPayment={() => { if (!selectedBoarder) return; setDetailId(null); onRecordPayment(selectedBoarder.id); }} onMoveOut={() => selectedBoarder && openConfirmation("moveout", selectedBoarder)} />
    <BoarderFormDialog open={addOpen} title="Add boarder" description="Create a boarder record, then assign a vacant bedspace." form={form} setForm={setForm} errors={formErrors} busy={mutating} onClose={closeForm} onSave={saveNew} saveLabel="Add boarder" />
    <BoarderFormDialog open={Boolean(edit)} title="Edit boarder" description="Contact changes immediately update the owner directory." form={form} setForm={setForm} errors={formErrors} busy={mutating} onClose={closeForm} onSave={saveEdit} saveLabel="Save changes" />
    <Dialog open={Boolean(transfer)} onOpenChange={(open) => !open && setTransfer(null)}><DialogContent className="assign-dialog"><DialogHeader><DialogTitle>{transfer?.status === "unassigned" ? "Assign" : "Transfer"} {transfer?.name}</DialogTitle><DialogDescription>Select a vacant bedspace. A transfer closes the previous occupancy record and starts a new one today.</DialogDescription></DialogHeader>{vacantBeds.length ? <label className="form-field"><span>Available bedspace</span><select className="form-select" value={targetBedId} onChange={(event) => setTargetBedId(event.target.value)}>{vacantBeds.map((bed) => <option key={bed.id} value={bed.id}>{bed.room} · {bed.label} — {peso.format(bed.rent)}</option>)}</select></label> : <div className="form-message error">No vacant bedspaces are available.</div>}<DialogFooter><Button variant="outline" onClick={() => setTransfer(null)}>Cancel</Button><Button className="lime-button" disabled={mutating || !targetBedId} onClick={saveTransfer}>{mutating ? "Saving…" : transfer?.status === "unassigned" ? "Assign bedspace" : "Confirm transfer"}</Button></DialogFooter></DialogContent></Dialog>
    <ConfirmDialog open={Boolean(confirm)} onOpenChange={(open) => !open && setConfirm(null)} destructive={confirm?.type !== "moveout"} busy={mutating} title={confirm?.type === "moveout" ? `Move out ${confirm.boarder.name}?` : confirm?.type === "archive" ? `Archive ${confirm?.boarder.name}?` : `Delete ${confirm?.boarder.name}?`} description={confirm?.type === "moveout" ? "Their active occupancy ends today and the bedspace becomes vacant. Payment history remains available." : confirm?.type === "archive" ? "Any active occupancy ends today. Historical records are preserved." : "Records with occupancy or payment history are archived instead of permanently erased."} confirmLabel={confirm?.type === "moveout" ? "Record move-out" : confirm?.type === "archive" ? "Archive boarder" : "Delete record"} onConfirm={runConfirm} />
  </div>;
}

function BoarderRow({ tenant, hasVacancy, onView, onEdit, onTransfer, onMoveOut, onArchive, onDelete }: { tenant: Tenant; hasVacancy: boolean; onView: () => void; onEdit: () => void; onTransfer: () => void; onMoveOut: () => void; onArchive: () => void; onDelete: () => void }) {
  const assigned = ["current", "overdue"].includes(tenant.status);
  const transferLabel = tenant.status === "unassigned" ? "Assign bedspace" : "Transfer bedspace";
  return <article className="tenant-row tenant-row-actions">
    <span className="avatar-md">{tenant.initials}</span>
    <span className="tenant-primary"><button type="button" className="tenant-name-button" onClick={onView}>{tenant.name}</button><small>{tenant.phone}</small></span>
    <span className="tenant-bed"><small>Assigned bed</small><strong>{tenant.bed}</strong></span>
    <span className="tenant-balance"><small>Balance</small><strong className={tenant.balance ? "balance-due" : "balance-clear"}>{tenant.balance ? peso.format(tenant.balance) : "Clear"}</strong></span>
    <span className={`status-chip ${tenant.status}`}>{tenant.status}</span>
    <div className="row-actions desktop-row-actions"><button onClick={onView} title="View boarder" aria-label={`View ${tenant.name}`}><Eye /></button>{tenant.status !== "inactive" && <button disabled={!hasVacancy} onClick={onTransfer} title={transferLabel} aria-label={`${transferLabel} for ${tenant.name}`}><ArrowRightLeft /></button>}<details className="desktop-overflow-menu"><summary aria-label={`More actions for ${tenant.name}`}><MoreHorizontal /></summary><div><button onClick={onEdit}><Pencil /> Edit details</button>{assigned && <button onClick={onMoveOut}><LogOut /> Record move-out</button>}{tenant.status !== "inactive" ? <button className="danger" onClick={onArchive}><Archive /> Archive boarder</button> : <button className="danger" onClick={onDelete}><Trash2 /> Delete boarder</button>}</div></details></div>
    <div className="tenant-mobile-details"><span><small>Bedspace</small><strong>{tenant.bed}</strong></span><span><small>Balance</small><strong className={tenant.balance ? "balance-due" : "balance-clear"}>{tenant.balance ? peso.format(tenant.balance) : "Clear"}</strong></span></div>
    <div className="tenant-mobile-actions"><button className="mobile-primary-action" onClick={onView}><Eye /> View details</button><details className="mobile-overflow-menu"><summary aria-label={`More actions for ${tenant.name}`}><MoreHorizontal /></summary><div>{tenant.status !== "inactive" && <button disabled={!hasVacancy} onClick={onTransfer}><ArrowRightLeft /> {hasVacancy ? transferLabel : "No vacant bedspace"}</button>}<button onClick={onEdit}><Pencil /> Edit details</button>{assigned && <button onClick={onMoveOut}><LogOut /> Record move-out</button>}{tenant.status !== "inactive" ? <button className="danger" onClick={onArchive}><Archive /> Archive boarder</button> : <button className="danger" onClick={onDelete}><Trash2 /> Delete boarder</button>}</div></details></div>
  </article>;
}

function BoarderDetailsDrawer({ boarder, payments, charges, lease, history, needs, timezone, tab, setTab, hasVacancy, onClose, onEdit, onTransfer, onRecordPayment, onMoveOut }: { boarder: Tenant | null; payments: Payment[]; charges: BillingCharge[]; lease: LeaseTerm | null; history: BoarderOccupancy[]; needs: Need[]; timezone: string; tab: DetailTab; setTab: (tab: DetailTab) => void; hasVacancy: boolean; onClose: () => void; onEdit: () => void; onTransfer: () => void; onRecordPayment: () => void; onMoveOut: () => void }) {
  const paymentPages = usePagination(payments, 5, boarder?.id);
  const historyPages = usePagination(history, 5, boarder?.id);
  const needPages = usePagination(needs, 5, boarder?.id);
  if (!boarder) return null;
  const assigned = ["current", "overdue"].includes(boarder.status);
  const currentStay = history.find((item) => item.status === "active");
  const currentMonth = zonedMonthKey(new Date(), timezone);
  const paidThisMonth = payments.filter((item) => item.status === "paid").reduce((total, item) => total + (item.allocations?.filter((allocation) => ["rent", "advance_rent"].includes(allocation.chargeType || "") && allocation.periodStart?.startsWith(currentMonth)).reduce((subtotal, allocation) => subtotal + allocation.amount, 0) || 0), 0);
  const lastPayment = payments.find((item) => item.status === "paid");
  const openNeeds = needs.filter((item) => item.status !== "resolved").length;
  const openCharges = charges.filter((item) => ["open", "partial"].includes(item.status)).sort((a, b) => a.dueDate.localeCompare(b.dueDate));
  const depositHeld = charges.filter((item) => item.type === "security_deposit" && item.status !== "void").reduce((total, item) => total + item.paidAmount, 0);
  const billable = assigned || openCharges.length > 0;
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="boarder-drawer" aria-label={`Boarder details for ${boarder.name}`}>
    <header className="boarder-drawer-header"><span className="profile-avatar boarder-drawer-avatar">{boarder.initials}</span><div><span className={`status-chip ${boarder.status}`}>{boarder.status}</span><h2>{boarder.name}</h2><p>{boarder.bed}</p></div></header>
    <div className="boarder-quick-actions">{billable && <Button className="lime-button" onClick={onRecordPayment}><WalletCards /> Record payment</Button>}{boarder.status !== "inactive" && <Button variant="outline" disabled={!hasVacancy} onClick={onTransfer}><ArrowRightLeft />{boarder.status === "unassigned" ? "Assign bedspace" : "Transfer"}</Button>}<Button variant="outline" onClick={onEdit}><Pencil /> Edit</Button><Button variant="outline" onClick={() => window.print()}><Printer /> Statement</Button>{assigned && <Button variant="outline" className="moveout-button" onClick={onMoveOut}><LogOut /> Move out</Button>}</div>
    <nav className="boarder-detail-tabs" role="tablist" aria-label="Boarder details">{(["overview", "lease", "payments", "history", "requests"] as const).map((item) => <button type="button" role="tab" id={`boarder-tab-${item}`} aria-controls={`boarder-panel-${item}`} key={item} className={tab === item ? "active" : ""} aria-selected={tab === item} tabIndex={tab === item ? 0 : -1} onClick={() => setTab(item)}>{item}{item === "lease" && openCharges.length > 0 && <b>{openCharges.length}</b>}{item === "payments" && payments.length > 0 && <b>{payments.length}</b>}{item === "history" && history.length > 0 && <b>{history.length}</b>}{item === "requests" && needs.length > 0 && <b>{needs.length}</b>}</button>)}</nav>

    {tab === "overview" && <div className="boarder-detail-content" role="tabpanel" id="boarder-panel-overview" aria-labelledby="boarder-tab-overview">
      <section className="boarder-detail-metrics"><span><BedDouble /><small>Current bedspace</small><strong>{boarder.bed}</strong></span><span><WalletCards /><small>Current balance</small><strong className={boarder.balance ? "balance-due" : "balance-clear"}>{boarder.balance ? peso.format(boarder.balance) : "Clear"}</strong></span><span><ReceiptText /><small>Rent paid this period</small><strong>{peso.format(paidThisMonth)}</strong></span></section>
      <section className="boarder-detail-card"><div className="detail-card-heading"><div><span className="eyebrow">CONTACT</span><h3>Contact information</h3></div></div><div className="boarder-contact-list"><a href={boarder.phone === "No phone" ? undefined : `tel:${boarder.phone}`} aria-disabled={boarder.phone === "No phone"}><Phone /><span><small>Phone number</small><strong>{boarder.phone}</strong></span></a><a href={boarder.email ? `mailto:${boarder.email}` : undefined} aria-disabled={!boarder.email}><Mail /><span><small>Email address</small><strong>{boarder.email || "No email added"}</strong></span></a></div></section>
      <section className="boarder-detail-card"><div className="detail-card-heading"><div><span className="eyebrow">CURRENT STAY</span><h3>Occupancy summary</h3></div></div>{currentStay ? <div className="stay-summary"><span><CalendarDays /><small>Move-in date</small><strong>{dateLabel(currentStay.startDate)}</strong></span><span><BedDouble /><small>Monthly rent</small><strong>{peso.format(currentStay.monthlyRent)}</strong></span><span><Clock3 /><small>Latest payment</small><strong>{lastPayment ? `${lastPayment.date} · ${peso.format(lastPayment.amount)}` : "No paid record"}</strong></span></div> : <div className="detail-empty"><History /><strong>No active occupancy</strong><span>Past stays remain available under History.</span></div>}</section>
      {openNeeds > 0 && <button className="boarder-attention-card" onClick={() => setTab("requests")}><CircleAlert /><span><strong>{openNeeds} open {openNeeds === 1 ? "request" : "requests"}</strong><small>Review maintenance items connected to this boarder</small></span></button>}
    </div>}

    {tab === "lease" && <div className="boarder-detail-content" role="tabpanel" id="boarder-panel-lease" aria-labelledby="boarder-tab-lease">
      {lease ? <section className="boarder-detail-card"><div className="detail-card-heading"><div><span className="eyebrow">LEASE TERMS</span><h3>Active billing agreement</h3></div><span className="status-chip current">active</span></div><div className="lease-detail-grid"><span><WalletCards /><small>Monthly rent</small><strong>{peso.format(lease.monthlyRent)}</strong></span><span><CalendarDays /><small>Monthly due date</small><strong>Day {lease.rentDueDay}</strong></span><span><Clock3 /><small>Grace period</small><strong>{lease.gracePeriodDays ? `${lease.gracePeriodDays} days` : "None"}</strong></span><span><CalendarDays /><small>Effective from</small><strong>{dateLabel(lease.effectiveFrom)}</strong></span><span><Landmark /><small>Advance rent agreed</small><strong>{peso.format(lease.advanceRentAmount)}</strong></span><span><ShieldCheck /><small>Security deposit agreed</small><strong>{peso.format(lease.securityDepositAmount)}</strong></span></div><div className="lease-safeguard"><ShieldCheck /><span><strong>{lease.rentControlCovered ? "Rent-control safeguards enabled" : "Custom lease terms"}</strong><small>{lease.rentControlCovered ? "Advance and deposit caps are enforced for this lease." : "Review the signed agreement and applicable law before changing financial terms."}</small></span></div></section> : <section className="boarder-detail-card"><div className="detail-empty"><Landmark /><strong>No active lease</strong><span>{openCharges.length ? "The stay has ended, but outstanding charges remain available for settlement." : "Assign a vacant bedspace to create lease terms and opening charges together."}</span>{boarder.status === "unassigned" && hasVacancy && !openCharges.length && <Button className="lime-button" onClick={onTransfer}>Choose bedspace</Button>}</div></section>}
      <section className="boarder-detail-card"><div className="detail-card-heading"><div><span className="eyebrow">CHARGE LEDGER</span><h3>Open obligations</h3></div><span className="deposit-held">{peso.format(depositHeld)} deposit held</span></div><div className="lease-charge-list">{openCharges.map((charge) => <div key={charge.id}><span className={`charge-type-icon ${charge.type}`}>{charge.type === "security_deposit" ? <ShieldCheck /> : charge.type === "other" ? <Landmark /> : <CalendarDays />}</span><span><strong>{charge.description}</strong><small>Due {dateLabel(charge.dueDate)} · {peso.format(charge.paidAmount)} paid</small></span><span><strong>{peso.format(charge.balance)}</strong><small>{charge.status}</small></span></div>)}{!openCharges.length && <div className="detail-empty compact"><ShieldCheck /><strong>No open charges</strong><span>This boarder’s generated obligations are fully paid.</span></div>}</div></section>
    </div>}

    {tab === "payments" && <div className="boarder-detail-content" role="tabpanel" id="boarder-panel-payments" aria-labelledby="boarder-tab-payments"><section className="boarder-detail-card"><div className="detail-card-heading"><div><span className="eyebrow">PAYMENT HISTORY</span><h3>Allocated transactions</h3></div>{billable && <Button size="sm" className="lime-button" onClick={onRecordPayment}><Plus /> Record</Button>}</div><div className="detail-record-list">{paymentPages.visible.map((payment) => <div className="detail-payment-row" key={payment.id}><span className="detail-record-icon"><ReceiptText /></span><div><strong>{payment.allocationLabel || payment.period}</strong><small>{payment.date} · {payment.method}{payment.receiptNumber ? ` · ${payment.receiptNumber}` : ""}</small></div><span><strong>{peso.format(payment.amount)}</strong><small className={`status-chip ${payment.status}`}>{payment.status}</small></span></div>)}{!payments.length && <div className="detail-empty"><ReceiptText /><strong>No payment history</strong><span>Paid, pending, and voided allocated payments will appear here.</span></div>}</div><PaginationControls {...paymentPages} total={payments.length} label="payments" onPageChange={paymentPages.setPage} /></section></div>}

    {tab === "history" && <div className="boarder-detail-content" role="tabpanel" id="boarder-panel-history" aria-labelledby="boarder-tab-history"><section className="boarder-detail-card"><div className="detail-card-heading"><div><span className="eyebrow">OCCUPANCY HISTORY</span><h3>Rooms and transfers</h3></div></div><div className="occupancy-timeline">{historyPages.visible.map((stay) => <div key={stay.id}><span className={`timeline-dot ${stay.status}`} /><div><strong>{stay.bedspace}</strong><small>{dateLabel(stay.startDate)} – {dateLabel(stay.endDate)}</small><span>{peso.format(stay.monthlyRent)} monthly rent</span></div><span className={`status-chip ${stay.status === "active" ? "current" : "inactive"}`}>{stay.status}</span></div>)}{!history.length && <div className="detail-empty"><History /><strong>No occupancy history</strong><span>Assignments and transfers will build a permanent timeline here.</span></div>}</div><PaginationControls {...historyPages} total={history.length} label="stays" onPageChange={historyPages.setPage} /></section></div>}

    {tab === "requests" && <div className="boarder-detail-content" role="tabpanel" id="boarder-panel-requests" aria-labelledby="boarder-tab-requests"><section className="boarder-detail-card"><div className="detail-card-heading"><div><span className="eyebrow">LINKED REQUESTS</span><h3>Maintenance and needs</h3></div></div><div className="detail-record-list">{needPages.visible.map((need) => <div className="detail-need-row" key={need.id}><span className={`priority-marker ${need.priority}`} /><div><strong>{need.title}</strong><small>{need.location} · Reported {need.reported}</small></div><span className={`status-chip ${need.status.replace(" ", "-")}`}>{need.status}</span></div>)}{!needs.length && <div className="detail-empty"><CircleAlert /><strong>No linked requests</strong><span>Requests associated with this boarder will appear here.</span></div>}</div><PaginationControls {...needPages} total={needs.length} label="requests" onPageChange={needPages.setPage} /></section></div>}
  </DialogContent></Dialog>;
}

function BoarderFormDialog({ open, title, description, form, setForm, errors, busy, onClose, onSave, saveLabel }: { open: boolean; title: string; description: string; form: { fullName: string; phone: string; email: string }; setForm: Dispatch<SetStateAction<{ fullName: string; phone: string; email: string }>>; errors: { name: string; phone: string; email: string }; busy: boolean; onClose: () => void; onSave: () => void; saveLabel: string; }) {
  const invalid = Boolean(errors.name || errors.phone || errors.email);
  return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent className="assign-dialog form-dialog"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader><div className="form-grid"><label className="form-field form-field-wide"><span>Full name</span><Input autoComplete="name" maxLength={100} aria-invalid={Boolean(errors.name)} aria-describedby="boarder-name-error" value={form.fullName} onChange={(event) => setForm((value) => ({ ...value, fullName: event.target.value }))} /><FieldError id="boarder-name-error">{errors.name}</FieldError></label><label className="form-field"><span>Phone number <small>Optional</small></span><Input type="tel" inputMode="tel" autoComplete="tel" maxLength={20} aria-invalid={Boolean(errors.phone)} aria-describedby="boarder-phone-error" value={form.phone} onChange={(event) => setForm((value) => ({ ...value, phone: normalizePhone(event.target.value) }))} /><FieldError id="boarder-phone-error">{errors.phone}</FieldError></label><label className="form-field"><span>Email <small>Optional</small></span><Input type="email" autoComplete="email" maxLength={160} aria-invalid={Boolean(errors.email)} aria-describedby="boarder-email-error" value={form.email} onChange={(event) => setForm((value) => ({ ...value, email: event.target.value }))} /><FieldError id="boarder-email-error">{errors.email}</FieldError></label></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button className="lime-button" disabled={busy || invalid} onClick={onSave}>{busy ? "Saving…" : saveLabel}</Button></DialogFooter></DialogContent></Dialog>;
}
